### PR TITLE
Use absolute paths for uploads and db

### LINKED ISSUE #25: Database is in an unexpected place
On my production server database directory is in the root of the system `/.db/pages.db`. While I am trying to find it in project's directory `./.db/pages.db`.

Need to compose path to database file via `path.resolve()`.

https://github.com/codex-team/codex.docs/blob/d61818761e4284aac02a1fbc7e0170dbbf35b524/src/utils/database/pages.js#L4

### PR DESCRIPTION
**Pull request by n0str**
resolves #25

### CODE REVIEW

**Review by nikmel2803 — COMMENTED** [review]
It is better to leave it possible to specify the relative path.
As a solution, you can check for `/` at the beginning of the path

**Review by nikmel2803 — APPROVED** [review]

File: src/backend/controllers/transport.ts [hunk 1]
```diff
@@ -34,20 +34,23 @@ class Transport {
...
       size,
       mimetype,
+      url,
     });
 
     await file.save();
 
     let response = file.data;
 
+    console.log(file)
```
Comment (neSpecc) [inline src/backend/controllers/transport.ts:52]: logs

File: src/backend/models/file.ts [hunk 2]
```diff
@@ -10,6 +10,7 @@ const filesDb = database['files'];
  * @property {string} filename - name of uploaded file
  * @property {string} path - path to uploaded file
  * @property {string} mimetype - file MIME type
+ * @property {string} url - file url
```
Comment (neSpecc) [inline src/backend/models/file.ts:13]: the description is not clear. Where is the URL got from?

File: src/backend/routes/api/transport.ts [hunk 3]
```diff
@@ -77,10 +77,17 @@ router.post('/transport/image', imageUploader, async (req: Request, res: Respons
     return;
   }
 
+  const fileData = {
+    ...req.files.image[0],
+    url: '/uploads/' + req.files.image[0].filename,
```
Comment (neSpecc) [inline src/backend/routes/api/transport.ts:82]: why do we need to hardcode the URL at the Database instead of using the file id of the name?

File: src/backend/views/auth.twig [hunk 4]
```diff
@@ -8,6 +8,9 @@
     <p>
       Enter a password to access pages editing
     </p>
+    <p>
+      {{ header }}
```
Comment (neSpecc) [inline src/backend/views/auth.twig:12]: what is it?

File: src/backend/app.ts [hunk 5]
```diff
@@ -20,6 +21,7 @@ app.use(express.json());
 app.use(express.urlencoded({ extended: true }));
 app.use(cookieParser());
 app.use(express.static(path.join(__dirname, '../../public')));
+app.use('/uploads', express.static(config.get('uploads')));
```
Comment (neSpecc) [inline src/backend/app.ts:24]: is it breaks the backward capability for the previously uploaded images?

**Review by neSpecc — CHANGES_REQUESTED** [review]

File: src/backend/routes/api/transport.ts (hunk 3 above)
Comment (nikmel2803) [reply src/backend/routes/api/transport.ts:82]: because all static files are serving from uploads directory
before this change file url depends on uploads folder name, which is wrong

File: src/backend/app.ts (hunk 5 above)
Comment (nikmel2803) [reply src/backend/app.ts:24]: nope

File: src/backend/views/auth.twig (hunk 4 above)
Comment (nikmel2803) [reply src/backend/views/auth.twig:12]: Alexander made it to see what error occurs

File: src/backend/routes/api/transport.ts (hunk 3 above)
Comment (neSpecc) [reply src/backend/routes/api/transport.ts:82]: but why do we need to store the `/uploads/` at the db? What if we will change it in the future? I think we can compose the URL on the fly by the client-side app.

Comment (nikmel2803) [reply src/backend/routes/api/transport.ts:82]: I guess you're right, we can resolve it in the separate issue
With this change I just resolve issue when uploads stores in folder with different name

**Review by neSpecc — APPROVED** [review]
Fix is ok. The **hardcode** should be removed due tu #184
